/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jni_TestJni_InnerTestClass */

#ifndef _Included_org_example_jni_TestJni_InnerTestClass
#define _Included_org_example_jni_TestJni_InnerTestClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
