/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jni_TestJni */

#ifndef _Included_org_example_jni_TestJni
#define _Included_org_example_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_jni_TestJni
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_jni_TestJni_hello
  (JNIEnv *, jclass);

/*
 * Class:     org_example_jni_TestJni
 * Method:    hello2
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_jni_TestJni_hello2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_example_jni_TestJni
 * Method:    hello3
 * Signature: ([II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_jni_TestJni_hello3
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     org_example_jni_TestJni
 * Method:    callInner
 * Signature: (Lorg/example/jni/TestJni/InnerTestClass;)V
 */
JNIEXPORT void JNICALL Java_org_example_jni_TestJni_callInner
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
