/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jni_TestJni */

#ifndef _Included_org_example_jni_TestJni
#define _Included_org_example_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_jni_TestJni
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_jni_TestJni_hello
  (JNIEnv *, jclass);

/*
 * Class:     org_example_jni_TestJni
 * Method:    hello2
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_jni_TestJni_hello2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_example_jni_TestJni
 * Method:    hello3
 * Signature: ([Ljava/lang/String;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_jni_TestJni_hello3
  (JNIEnv *, jclass, jobjectArray, jintArray);

/*
 * Class:     org_example_jni_TestJni
 * Method:    hello4
 * Signature: ([Ljava/lang/String;[II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_jni_TestJni_hello4
  (JNIEnv *, jclass, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
